services:
  backend:
    build:
      context: ./backend
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - OPENAI_MODEL=gpt-3.5-turbo
        - ADMIN_REGISTRATION_SECRET=${ADMIN_REGISTRATION_SECRET:-admin123}
        - MAX_DOCUMENT_SIZE=${MAX_DOCUMENT_SIZE:-4000}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./storage:/app/storage
      - ./data:/app/data
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8000
        - NODE_ENV=development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
